fofb_processing/cheby: clean registers api
lnls-dig/fofb-ctrl-gw pull request #12
Opened 2023-02-15 13:34 UTC by guilhermerc

By the time this layout was drawn, cheby had a bug that didn't allow the usage of 'repeat' statements if the design contained memories. The workaround was to flatenize the per-channel registers/memories declarations.

The issue mentioned above doesn't appear on cheby 1.4.0. So, this commit cleans up the registers api.

2023-02-15 19:41 UTC, guilhermerc commented
This PR won't be merged until [erics](https://github.com/lnls-dig/erics) is running on our crates.

2023-02-27 13:27 UTC, Palmitoxico requested changes

2023-02-27 13:27 UTC, Palmitoxico commented on hdl/modules/fofb_ctrl_pkg.vhd
> +    addr_last     => x"000000000000CFFF",
Please change addr_last to 0xFFFF

2023-03-01 13:15 UTC, guilhermerc commented on hdl/modules/fofb_processing/fofb_processing_channel.vhd
> +          elsif sp_filtered_samples = sp_decim_ratio_i + 1 then
@Palmitoxico , I've also addressed your suggestion to let '0' as a valid decimation ratio.

2023-03-03 21:17 UTC, guilhermerc commented
I think I'm done for features 1 and 2.

2023-04-17 15:08 UTC, merged