FOFB system identification features: cheby and xwb_fofb_sys_id
lnls-dig/fofb-ctrl-gw pull request #19
Opened 2023-04-03 21:38 UTC by guilhermerc

2023-04-05 14:29 UTC, ericonr commented on hdl/modules/fofb_sys_id/cheby/wb_fofb_sys_id_regs.cheby
> +                Two instances of base_idx register, one for each axis (x or y)
"x and y"?

2023-04-05 14:29 UTC, ericonr commented on hdl/modules/fofb_sys_id/cheby/wb_fofb_sys_id_regs.cheby
> +                      Togheter with max_num_cte, defines the valid range of BPM
Together

2023-04-05 17:26 UTC, guilhermerc commented
The current implementation of `xwb_fofb_sys_id` exposes only the essential registers that allow us to test the hole acquisition  scheme.

2023-04-05 17:51 UTC, Palmitoxico requested changes

2023-04-05 17:51 UTC, Palmitoxico commented on hdl/testbench/xwb_fofb_sys_id/Manifest.py
> +    "sim_vhdl_sim_wishbone.vhd",
Please replace `sim_vhdl_sim_wishbone.vhd` with `../../ip_cores/general-cores/sim/vhdl/sim_vhdl_sim_wishbone.vhd`.

2023-04-05 17:51 UTC, Palmitoxico commented on hdl/testbench/xwb_fofb_sys_id/sim_vhdl_sim_wishbone.vhd
This file is already provided by the `general-cores` submodule.

2023-04-05 17:51 UTC, Palmitoxico commented on hdl/modules/fofb_sys_id/cheby/wb_fofb_sys_id_regs.cheby
> +              children:
There is no need to declare a `children` if the register has only one field.

2023-04-05 17:51 UTC, Palmitoxico commented on hdl/modules/fofb_sys_id/cheby/wb_fofb_sys_id_regs.cheby
> +                          range: 8-0
Please change this to use a single register without sub-fields that uses the BPM id number and automatically drive the bpm_flatenaizer correctly for both axis. This makes the interface simpler and eliminates possible bugs in the software layer.

2023-04-05 17:51 UTC, Palmitoxico commented on hdl/modules/fofb_sys_id/xwb_fofb_sys_id.vhd
> +  inst_0_bpm_pos_flatenizer : bpm_pos_flatenizer
Just food for thought: I see component instance labels almost always starting with `cmp_`, but I don't know if it is a good convention to begin with.

2023-04-05 20:45 UTC, guilhermerc commented on hdl/modules/fofb_sys_id/xwb_fofb_sys_id.vhd
> +  inst_0_bpm_pos_flatenizer : bpm_pos_flatenizer
As per Table 4 of "Guidelines for VHDL Coding", 2011-04-19 (couldn't find the link :/), using `cmp_` is recommended indeed.

2023-04-06 19:29 UTC, guilhermerc commented
@ericonr, the temporary ABI is now defined. Could you (temporarily) support these regs on uhal/erics?

2023-04-06 19:45 UTC, Palmitoxico requested changes

2023-04-06 19:45 UTC, Palmitoxico commented on hdl/modules/fofb_sys_id/xwb_fofb_sys_id.vhd
> +    bpm_pos_flat_1_rcvd_o : out std_logic_vector(g_MAX_NUM_BPM_POS-1 downto 0);
Please use more descriptive signal names for the BPM flatenizer instances, reflecting the axis it will process.

2023-04-06 19:46 UTC, Palmitoxico approved these changes
:+1:

2023-04-06 20:48 UTC, guilhermerc commented on hdl/modules/fofb_sys_id/xwb_fofb_sys_id.vhd
> +    g_MAX_NUM_BPM_POS     : natural range 1 to 2**(natural(c_SP_COEFF_RAM_ADDR_WIDTH)) := 16;
I actually don't like this generic name. Maybe `g_MAX_NUM_P2P_BPM_POS`  (and use half of it on each bpm_pos_flatenizer instance) would be better.

2023-04-11 16:22 UTC, ericonr commented on hdl/top/afc_ref_design_gen/afc_ref_fofb_ctrl_gen.vhd
> +    -- TODO: These bits should be filled with channels 11-8, but they aren't not instantiated
I think this comment has a double negation.

2023-04-11 16:51 UTC, ericonr commented on hdl/top/afc_ref_design_gen/afc_ref_fofb_ctrl_gen.vhd
> +    bpm_pos_flat_x_rcvd & bpm_pos_flat_y_rcvd &                                                                                                             -- [DEBUG] Flatenizers' 'received' flag (64
Is it possible for us to receive the X position but not the Y one? Would it make sense to expose only one bit per BPM?

2023-04-12 16:58 UTC, guilhermerc commented on hdl/top/afc_ref_design_gen/afc_ref_fofb_ctrl_gen.vhd
> +    bpm_pos_flat_x_rcvd & bpm_pos_flat_y_rcvd &                                                                                                             -- [DEBUG] Flatenizers' 'received' flag (64
As we talked, these signals come from different flatenizers, so they bring uncorrelated info

2023-04-17 12:56 UTC, ericonr approved these changes
I think I'd like to refer to this PR / its last commit when finishing up my own PR in uHAL. Do you think we are close to merging?

2023-04-17 12:56 UTC, ericonr commented on hdl/top/afc_ref_design_gen/afc_ref_fofb_ctrl_gen.vhd
> +    std_logic_vector(bpm_pos_flat_x(3)) & std_logic_vector(bpm_pos_flat_x(2)) & std_logic_vector(bpm_pos_flat_x(1)) & std_logic_vector(bpm_pos_flat_x(0));
I have confirmed that all X and Y positions are working, as well as the setpoints and the timeframe value.

Have yet to test out the BPMId base register, because that has to be implemented yet.

2023-04-17 16:50 UTC, merged