Allowed x-y coupling coefficients on fofb processing
lnls-dig/fofb-ctrl-gw pull request #7
Opened 2022-08-29 14:05 UTC by guilhermerc

Instead of feeding fofb processing channels with bpm data of the same
axis it is controlling, use all bpm data. This allows x-y coupling
treatment.

2022-09-05 13:05 UTC, guilhermerc commented on hdl/top/afc_ref_design_gen/afc_ref_fofb_ctrl_gen.vhd
> +  cmp_generic_sync_fifo: generic_sync_fifo
@Palmitoxico plans to refactor `xwb_fofb_processing` so it doesn't use `fofb_fod_dat(c_FOFB_CC_FMC_OR_RTM_ID)` clock anymore. Therefore, in order to safely cross clock domains, this fifo has to be asynchronous.

2022-09-05 19:42 UTC, guilhermerc commented on hdl/top/afc_ref_design_gen/afc_ref_fofb_ctrl_gen.vhd
> +  cmp_generic_sync_fifo: generic_sync_fifo
Also, `timeframe_end(c_FOFB_CC_FMC_OR_RTM_ID)` has, somehow, to be queued too.

2022-09-09 13:31 UTC, Palmitoxico requested changes

2022-09-09 13:31 UTC, Palmitoxico commented on hdl/top/afc_ref_design_gen/afc_ref_fofb_ctrl_gen.vhd
> +            if fofb_proc_busy /= '1' and serialize_fifo_empty /= '1' then
Checking `fofb_proc_busy` here will work, but is a dangerous practice as its busy status can change in the next clock cycle. Read it in the `DRIVE_X_DATA_OR_TIMEFRAME_END` and `DRIVE_Y` states.

2022-09-09 13:31 UTC, Palmitoxico commented on hdl/top/afc_ref_design_gen/afc_ref_fofb_ctrl_gen.vhd
> +          when CONSUME =>
This state could be optimised out.

2022-09-09 13:31 UTC, Palmitoxico commented on hdl/top/afc_ref_design_gen/afc_ref_fofb_ctrl_gen.vhd
> +              for i in 0 to c_FOFB_CHANNELS-1
Again, unnecessary for loop.

2022-09-09 13:31 UTC, Palmitoxico commented on hdl/top/afc_ref_design_gen/afc_ref_fofb_ctrl_gen.vhd
> +            for i in 0 to c_FOFB_CHANNELS-1
Unnecessary for loop.

2022-09-09 13:31 UTC, Palmitoxico commented on hdl/top/afc_ref_design_gen/afc_ref_fofb_ctrl_gen.vhd
> +            for i in 0 to c_FOFB_CHANNELS-1
Unnecessary for loop.

2022-09-09 14:22 UTC, merged